apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-hello.labels" . | nindent 4 }}
spec:
  type: NodePort  # Change type to LoadBalancer
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "node-hello.selectorLabels" . | nindent 4 }}
