apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nodehello
spec:
  type: NodePort  
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nodehello
