image:
  repository: abhaykohli/nodehello-prod
  tag: 36
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

replicaCount: 1

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
