image:
  repository: abhaykohli/nodehello-prod
  tag: 23
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3000

replicaCount: 2

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
